baseURL = "https://mohdsaed.com/"
languageCode = "en-us"
title = "Mohammed Saed"
theme = "mohdsaed-dark"
enableGitInfo = true

[params]
	authorName = "Mohammed Saed"
	description = "Mohammed Saed's blog about computers, programming, travel and life."
	googleAnalytics = "G-3JLZPCJ09W"

[markup]
	[markup.goldmark]
		[markup.goldmark.parser]
			[markup.goldmark.parser.attribute]
				block = true
  [markup.tableOfContents]
    ordered = false
    startLevel = 2
    endLevel = 4
