baseURL = "https://mohdsaed.com/"
languageCode = "en-us"
title = "Mohammed Saed"
theme = "mohdsaed-dark"
enableGitInfo = true

[params]
	authorName = "Mohammed Saed"
	description = "Mohammed Saed's blog about computers, programming, travel and life."
	googleAnalytics = "G-3JLZPCJ09W"
  math = false

[markup]
	[markup.goldmark]
		[markup.goldmark.parser]
			[markup.goldmark.parser.attribute]
				block = true
	[markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
  [markup.tableOfContents]
    ordered = false
    startLevel = 2
    endLevel = 4
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'github-dark'
    tabWidth = 4
